version: '1.0'

# models configuration can be used by agents and prompts
models:
  standard-assistant:
    provider: azure_openai
    id: gpt-4-turbo
    version: '1.0'
    config:
      api_key: ${env:AZURE_OPENAI_KEY}
      endpoint: ${env:AZURE_OPENAI_ENDPOINT}
      deployment: cdp-analysis-gpt-4o
      api_version: 2023-12-01-preview
    params:
      temperature: 0.2
      max_tokens: 4096
      top_p: 0.95

tools:

  # OpenAPI tools
  openapi:
    opoint_api:
      schema_path: tools/openapi/opoint.schema.json
      version: '1.0'
      headers:
        Authorization: ${env:OPENAPI_OPOINT_API_KEY}
        Content-Type: application/json
        Accept: application/json
  
  # Azure AI Foundry agents as tools
  ai_foundry:
    default_project_endpoint: ${env:AZURE_AI_FOUNDRY_PROJECT_ENDPOINT}
    tools:
      bing_search:
        version: '1.0'
        type: bing
        description: Bing web search tool via Azure AI Foundry agent connection
        connection_ids:
          - ${env:BING_SEARCH_CONNECTION_ID}
        config:
            project_endpoint: ${ref:tools.ai_foundry.default_project_endpoint}
        
      opoint_api:
        version: '1.0'
        description: Opoint API integration via Azure AI Foundry agent connection
        type: openapi
        schema_path: tools/ai_foundry/opoint.schema.json
        connection_ids:
          - ${env:OPOINT_API_CONNECTION_ID}
        config:
            project_endpoint: ${ref:tools.ai_foundry.default_project_endpoint}
 
# agents configuration
agents:


  ai_foundry_opoint-agent:
    version: '1.0'
    name: ai_foundry_opoint-agent
    description: AI agent specialized in searching company information using Opoint API via Azure AI Foundry
    model: ${ref:models.standard-assistant}
    tools:
      - ${ref:tools.ai_foundry.tools.opoint_api}
    platform: azure_ai_foundry
    system_prompt:
      version: '1.0'
      path: prompts/opoint-agent.prompt.md

  sk-opoint-agent:
    version: '1.0'
    name: sk-opoint-agent
    description: AI agent specialized in searching company information using Opoint API
    model: ${ref:models.standard-assistant}
    tools:
      - ${ref:tools.openapi.opoint_api}
    platform: semantic-kernel
    system_prompt:
      version: '1.0'
      path: prompts/opoint-agent.prompt.md
  
  ai_foundry-search-agent:
    version: '1.0'
    name: ai_foundry-search-agent
    description: AI agent that combines web search and Opoint API and bing search.
    model: ${ref:models.standard-assistant}
    tools:
      - ${ref:tools.ai_foundry.tools.opoint_api}
      - ${ref:tools.ai_foundry.tools.bing_search}
    platform: azure_ai_foundry
    system_prompt:
      version: '1.0'
      path: prompts/combined-search-agent.prompt.md