name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Required for creating releases

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for changelog generation

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          body: |
            Changes in this Release
            - Update version to ${{ github.ref_name }}
            - See [CHANGELOG.md](CHANGELOG.md) for detailed changes

            ## Installation

            ```bash
            pip install agents-config==${{ github.ref_name }}
            ```

            ## What's Changed

            Full changelog: https://github.com/${{ github.repository }}/compare/v0.1.1...${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, 'rc') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') }}
          generate_release_notes: true
