name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for changelog generation

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - Update version to ${{ github.ref }}
            - See [CHANGELOG.md](CHANGELOG.md) for detailed changes

            ## Installation

            ```bash
            pip install agents-config==${{ github.ref_name }}
            ```

            ## What's Changed

            Full changelog: https://github.com/${{ github.repository }}/compare/v0.0.0...${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
